version: "3.3"
services:
  smart-front:
    build:
      context: 'smart-front'
      dockerfile: Dockerfile.prod
    container_name: smart_front
    depends_on:
      - smart-api
    ports:
      - '8000:8000'
  admin-front:
    build:
      context: 'admin-front'
      dockerfile: Dockerfile.prod
    container_name: admin-front
    depends_on:
      - admin-api
    ports:
      - '8001:8001'
  smart-api:
    build:
      context: 'smart-api'
      dockerfile: Dockerfile.prod
    command: npm start
    container_name: smart-api
    environment:
      NODE_ENV: production
    tty: true
    ports:
      - '8004:8004'
    depends_on:
      - mongo
  admin-api:
    build:
      context: 'admin-api'
      dockerfile: Dockerfile.prod
    command: npm start
    container_name: admin-api
    environment:
      NODE_ENV: production
    tty: true
    ports:
      - '8005:8005'
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
