version: "2"
services:
  smart-front:
    build:
      context: 'smart-front'
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./smart-front:/home/smart-front
      - /home/smart-front/node_modules
    command: ng server --watch --host 0.0.0.0
