version: '3'

services:

  recicla-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: recicla-api
    ports:
      - "3001:3000"
    networks:
      - db

networks:
  db:
    external: true

