module.exports = {
  MISSING: 'MISSING',
  TRAVELING: 'TRAVELING',
  LATE: 'LATE',
  NORMAL: 'NORMAL',
  INCORRECT_LOCAL: 'INCORRECT_LOCAL',
  LOW_BATTERY: 'LOW_BATTERY',
  INCONTIDA: 'INCONTIDA', // Sem rota e sem planta
  PERMANENCE_EXCEEDED: 'PERMANENCE_EXCEEDED',
};
