swagger: "2.0"
info:
  version: "0.0.1"
  description: "An project that has how the main functionality recover packings on the system through Beacons and Checkpoints"
  title: Reciclapac API Documentation
  contact:
   name: "David W. F. Santos"
   email: "david.santos@pe.senai.br"
   url: "http://pe.senai.br"
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
- name: "User"
  description: "All information about your Users"
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
