module.exports = {
    MISSING: 'AUSENTE',
    TRAVELING: 'VIAJANDO',
    LATE: 'ATRASADA',
    NORMAL: 'NORMAL',
    INCORRECT_LOCAL: 'LOCAL_INCORRETO',
    LOW_BATTERY: 'BATERIA_BAIXA',
    INCONTIDA: 'INCONTIDA', // Sem rota e sem planta
    PERMANENCE_EXCEEDED: 'TEMPO DE PERMANENCIA',
};
