FROM node:6.9.5

ENV HOME=/home

COPY package.json package-lock.json  $HOME/smart-front/

WORKDIR $HOME/smart-front

RUN npm cache clean && npm install --silent --progress=false

RUN npm install -g @angular/cli

COPY . $HOME/smart-front/

CMD ['npm','start']
