swagger: "2.0"
info:
  version: "0.0.1"
  description: "An project that has how the main functionality recover packings on the system through Beacons and Checkpoints"
  title: Reciclapac API Documentation
  contact:
   name: "David W. F. Santos"
   email: "david.santos@pe.senai.br"
   url: "http://pe.senai.br"
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
- name: "Home"
  description: "All information to Home page"
- name: "Maps"
  description: "All information to maps page"
- name: "Plant"
  description: "All information about your Plants"
- name: "Inventory"
  description: "All information about your Inventory"
- name: "Inventory Logistic"
  description: "All information about your Inventory to Op. Logistic"
- name: "Historic Movement"
  description: "All information about your Historic Movement"
- name: "Profile"
  description: "All information about your Profiles"
- name: "Project"
  description: "All information about your Projects"
- name: "Supplier"
  description: "All information about your Suppliers"
- name: "Settings"
  description: "All information about your Settings"
- name: "Logistic Operator"
  description: "All information about your Logistic Operators"
- name: "Route"
  description: "All information about your Routes"
- name: "Department"
  description: "All information about your Departments"
- name: "Packing"
  description: "All information about your Packings"
- name: "Tag"
  description: "All information about your Tags"
- name: "Historic Packings"
  description: "All information about your Historic Packings"
- name: "Alerts"
  description: "All information about your Alerts"
- name: "GC16"
  description: "All information about your GC16 registers"
- name: "Upload"
  description: "All information about your upload "
- name: "CEP"
  description: "Get address through CEP"
securityDefinitions:
  Bearer:
    type: apiKey
    in: header
    name: Authorization
