paths:
#-------------------------------------------START CRUD PROJECT ----------------------------------
  /project/retrieve/{project_id}:
      x-swagger-router-controller: project_controller
      get:
        tags:
          - "Project"
        summary: "Retrieve a project from the system"
        description: ""
        operationId: project_read
        security:
          - Bearer: []
        parameters:
        - in: "path"
          name: "project_id"
          description: "Retrieve a project related this project id"
          required: true
          type: string
        responses:
          200:
            description: "Successfully"
            schema:
              $ref: "#/definitions/SuccessResponse"
          400:
            description: "Client Error"
            schema:
              $ref: "#/definitions/Error400"
          500:
            description: "Server Error"
            schema:
              $ref: "#/definitions/Error500"
          default:
            description: "Error"
            schema:
              $ref: "#/definitions/ErrorResponse"
  /project/list/pagination/{limit}/{page}:
    x-swagger-router-controller: project_controller
    get:
      tags:
        - "Project"
      summary: "Retreive all projects from the system with pagination"
      description: ""
      operationId: project_listPagination
      security:
        - Bearer: []
      parameters:
      - in: "path"
        name: "limit"
        description: "The limit of projects that will be returned"
        required: true
        type: string
      - in: "path"
        name: "page"
        description: "Retrieve project related this page"
        required: true
        type: string
      - in: "query"
        name: "attr"
        description: "Retrieve project related this supplier id"
        required: false
        type: string
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/list/all:
    x-swagger-router-controller: project_controller
    get:
      tags:
        - "Project"
      summary: "Retreive all projects from the system"
      description: ""
      operationId: project_list
      security:
        - Bearer: []
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/create:
    x-swagger-router-controller: project_controller
    post:
      tags:
      - "Project"
      summary: "Add a new project on the system"
      description: ""
      operationId: project_create
      security:
        - Bearer: []
      parameters:
      - in: "body"
        name: "body"
        description: "Sample of project object that will be add to the system"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/create/array:
    x-swagger-router-controller: project_controller
    post:
      tags:
      - "Project"
      summary: "Add a array project on the system"
      description: ""
      operationId: project_create_array
      security:
        - Bearer: []
      parameters:
      - in: "body"
        name: "body"
        description: "Sample of array profile object that will be add to the system"
        required: true
        schema:
          $ref: "#/definitions/ArrayProject"
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/delete/{project_id}:
    x-swagger-router-controller: project_controller
    delete:
      tags:
      - "Project"
      summary: "Remove a project from the system"
      description: ""
      operationId: project_delete
      security:
        - Bearer: []
      parameters:
      - in: "path"
        name: "project_id"
        description: "Remove project related this project id"
        required: true
        type: string
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/update/{project_id}:
    x-swagger-router-controller: project_controller
    put:
      tags:
      - "Project"
      summary: "Update a project from the system"
      description: ""
      operationId: project_update
      security:
        - Bearer: []
      parameters:
      - in: "path"
        name: "project_id"
        description: "update project related this project id"
        required: true
        type: string
      - in: "body"
        name: "body"
        description: "The project object that will be modified"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "Client Error"
          schema:
            $ref: "#/definitions/Error400"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/Error500"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"

#-------------------------------------------FINISH CRUD PROJECT ----------------------------------
