paths:
#-------------------------------------------START CRUD SETTINGS----------------------------------
  /settings/retrieve:
      x-swagger-router-controller: settings_controller
      get:
        tags:
          - "Settings"
        summary: "Retrieve settings from the system"
        description: ""
        operationId: settings_retrieve
        security:
          - Bearer: []
        responses:
          200:
            description: "Successfully"
            schema:
              $ref: "#/definitions/SuccessResponse"
          400:
            description: "Client Error"
            schema:
              $ref: "#/definitions/Error400"
          500:
            description: "Server Error"
            schema:
              $ref: "#/definitions/Error500"
          default:
            description: "Error"
            schema:
              $ref: "#/definitions/ErrorResponse"
  /settings/update:
      x-swagger-router-controller: settings_controller
      put:
        tags:
          - "Settings"
        summary: "update settings from the system"
        description: ""
        operationId: settings_update
        security:
          - Bearer: []
        parameters:
          - in: "body"
            name: "body"
            description: "The setting object that will be modified"
            required: true
            schema:
              $ref: "#/definitions/Setting" 
        responses:
          200:
            description: "Successfully"
            schema:
              $ref: "#/definitions/SuccessResponse"
          400:
            description: "Client Error"
            schema:
              $ref: "#/definitions/Error400"
          500:
            description: "Server Error"
            schema:
              $ref: "#/definitions/Error500"
          default:
            description: "Error"
            schema:
              $ref: "#/definitions/ErrorResponse"
  

#-------------------------------------------FINISH CRUD SETTINGS----------------------------------
