paths:
#-------------------------------------------START CRUD PROJECT ----------------------------------
  /project/retrieve/{project_id}:
      x-swagger-router-controller: project_controller
      get:
        tags:
          - "Project"
        summary: "Get a project on the system"
        description: ""
        operationId: project_read
        parameters:
        - in: "path"
          name: "project_id"
          description: "The code that needs to be fetched"
          required: true
          type: string
        responses:
          200:
            description: "Message"
            schema:
              $ref: "#/definitions/SuccessResponse"
          default:
            description: "Error"
            schema:
              $ref: "#/definitions/ErrorResponse"
  /project/list/pagination/{limit}/{page}:
    x-swagger-router-controller: project_controller
    get:
      tags:
        - "Project"
      summary: "Get all projects on the system by pagination"
      description: ""
      operationId: project_listPagination
      parameters:
      - in: "path"
        name: "limit"
        description: "The limit of projects that will be returned"
        required: true
        type: string
      - in: "path"
        name: "page"
        description: "The especific page that returns projects related a this page"
        required: true
        type: string
      - in: "query"
        name: "attr"
        description: "The especific attr that returns packings related a this attr"
        required: false
        type: string
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/list/all:
    x-swagger-router-controller: project_controller
    get:
      tags:
        - "Project"
      summary: "Get all projects on the system"
      description: ""
      operationId: project_list
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/create:
    x-swagger-router-controller: project_controller
    post:
      tags:
      - "Project"
      summary: "Add a new project to the system"
      description: ""
      operationId: project_create
      parameters:
      - in: "body"
        name: "body"
        description: "project object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/create/array:
    x-swagger-router-controller: project_controller
    post:
      tags:
      - "Project"
      summary: "Add a array project to the system"
      description: ""
      operationId: project_create_array
      parameters:
      - in: "body"
        name: "body"
        description: "project array that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/ArrayProject"
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/delete/{project_id}:
    x-swagger-router-controller: project_controller
    delete:
      tags:
      - "Project"
      summary: "Remove a project on the system"
      description: ""
      operationId: project_delete
      parameters:
      - in: "path"
        name: "project_id"
        description: "The code that needs to be fetched"
        required: true
        type: string
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/update/{project_id}:
    x-swagger-router-controller: project_controller
    put:
      tags:
      - "Project"
      summary: "Update a project on the system"
      description: ""
      operationId: project_update
      parameters:
      - in: "path"
        name: "project_id"
        description: "The code that needs to be fetchede"
        required: true
        type: string
      - in: "body"
        name: "body"
        description: "The project object that will to be modified"
        required: true
        schema:
          $ref: "#/definitions/Project"
      responses:
        200:
          description: "Message"
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"

#-------------------------------------------FINISH CRUD PROJECT ----------------------------------
